services:
  whitebreeze:
    container_name: whitebreeze
    pull_policy: build
    build: 
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3000:3000 # host:container